"""First migration

Revision ID: 527c890b5436
Revises: 
Create Date: 2023-03-27 01:12:35.375336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527c890b5436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    # ### end Alembic commands ###
